apiVersion: v1
kind: ConfigMap
metadata:
  name: qclient-config
  namespace: client
data:
  application.yml: |
    server:
      port: 8080
    management:
      security:
        enabled: false
    qservice:
      url: http://qservice-dep.default.svc.cluster.local:8081/queueService
  bootstrap.yml: |
    spring:
      application:
        name: qclient-pi
      cloud:
        config:
          uri: http://spring-conf-dep.config:8888
        enabled: false
