apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: qclient-dep
  name: qclient-dep
  namespace: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qclient-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qclient-app
        role: qClient
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: qclient-config
      - name: log-volume
        emptyDir: {}
      initContainers:
      - image: busybox:1.28
        name: check-server
        #In lieu of liveness/readiness check not being able to resolve the DNS name (due to being called by Kubelet)
        command: ['sh', '-c', 'for i in $(seq 1 6); do  X=$(wget -q -O - http://qservice-dep.default:8081/actuator/health | grep "UP"); [ ! -z ${X} ] && break; sleep 10; done']
      containers:
      - image: gavinpollitt/qclient:arm-1.3
        name: qclient
        volumeMounts:
        - name: config-volume
          mountPath: /home/config
        - name: log-volume
          mountPath: /logs
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 20
      - image: busybox:1.28
        name: qlogger
        args: [/bin/sh, -c, 'tail -n+1 -f ./logs/qclient.log']
        volumeMounts:
        - name: log-volume
          mountPath: ./logs
