apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: qclient-dep
  name: qclient-dep
  namespace: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qclient-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qclient-app
        role: qClient
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: qclient-config
      containers:
      - image: gavinpollitt/qclient:arm-1.0
        name: qclient
        volumeMounts:
        - name: config-volume
          mountPath: /home/config

