apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zipkin-dep
  name: zipkin-dep
  namespace: config
spec:
  type: NodePort
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: zipkin-dep
