apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logreceiver-pod
  name: logreceiver-pod
  namespace: kube-system
spec:
  containers:
  - image: gavinpollitt/wiremock:arm-1.0
    name: logreceiver-pod
    ports:
    - containerPort: 8085
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    role: ops
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logreceiver
  name: logreceiver
  namespace: kube-system
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8085
  selector:
    run: logreceiver-pod
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
